# ***Import Pytorch***

In [1]:
import torch

In [2]:
torch.__version__

'2.5.1+cu121'

# **Scalar**

In [3]:
scaler = torch.tensor(8)
scaler

tensor(8)

In [4]:
scaler.ndim

0

In [5]:
scaler.item()

8

# **Vector**

In [6]:
vector = torch.tensor([8,8])
vector

tensor([8, 8])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

# **Matrix**

In [9]:
matrix = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([3, 3])

# **Tensor**

In [12]:
tensor = torch.tensor([[[1,2,3,9],[4,5,6,8],[7,8,9,9]]])
tensor

tensor([[[1, 2, 3, 9],
         [4, 5, 6, 8],
         [7, 8, 9, 9]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 4])

# **Random Tensor**

In [15]:
random_simple = torch.rand(size=(5,5))
random_simple

tensor([[0.8318, 0.6712, 0.1208, 0.7527, 0.0663],
        [0.8224, 0.9374, 0.5816, 0.9305, 0.1363],
        [0.2086, 0.9615, 0.6086, 0.2410, 0.8281],
        [0.3592, 0.7204, 0.7236, 0.6370, 0.4351],
        [0.1785, 0.7203, 0.1314, 0.3512, 0.1382]])

In [16]:
random_tensor = torch.randn(2,3)
random_tensor

tensor([[-0.1848,  0.1766,  0.1122],
        [-1.2428,  0.5591,  0.0277]])

In [17]:
big_random_tensor = torch.randn(5,2,3)
big_random_tensor

tensor([[[ 1.5758, -0.0969,  0.4825],
         [-1.7271,  0.3846, -0.7803]],

        [[ 0.4727, -0.0835, -1.4550],
         [ 0.7458, -0.2952, -0.1685]],

        [[ 1.5126,  0.7132,  2.0788],
         [ 1.8777, -2.6047,  0.4125]],

        [[-0.3003, -0.2943,  1.1093],
         [ 0.0293, -1.2788, -0.0343]],

        [[-0.9811, -0.9204, -1.8505],
         [-0.7885, -0.1388,  0.4524]]])

# **Zeros and Ones**

In [18]:
zeros = torch.zeros(5,2)
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [19]:
ones = torch.ones(2,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

# **Aranges and Tensor_like**

In [20]:
arange = torch.arange(1,15)
arange

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arange = torch.arange(1,10,2)
arange

tensor([1, 3, 5, 7, 9])

In [22]:
sample = torch.rand(9,9)
zeros_LK = torch.zeros_like(sample)
zeros_LK

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
ones_LK = torch.ones_like(zeros_LK)
ones_LK

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
eyes_tensor = torch.eye(5)
eyes_tensor

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

**torch Full**

In [27]:
torch_full = torch.full((5,5),7)
torch_full

tensor([[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]])

**Torch Linspace**

In [28]:
torch_linspace = torch.linspace(1,14,50)
torch_linspace

tensor([ 1.0000,  1.2653,  1.5306,  1.7959,  2.0612,  2.3265,  2.5918,  2.8571,
         3.1224,  3.3878,  3.6531,  3.9184,  4.1837,  4.4490,  4.7143,  4.9796,
         5.2449,  5.5102,  5.7755,  6.0408,  6.3061,  6.5714,  6.8367,  7.1020,
         7.3673,  7.6327,  7.8980,  8.1633,  8.4286,  8.6939,  8.9592,  9.2245,
         9.4898,  9.7551, 10.0204, 10.2857, 10.5510, 10.8163, 11.0816, 11.3469,
        11.6122, 11.8776, 12.1429, 12.4082, 12.6735, 12.9388, 13.2041, 13.4694,
        13.7347, 14.0000])

# **Tensor Datatypes**

In [31]:
default_datatype = torch.rand(2,3)
default_datatype.dtype

torch.float32

In [36]:
custom_datatype = torch.arange(.2,3,dtype=int)
custom_datatype.dtype

torch.int64

**Change Datatype**

In [38]:
before_change_datatype = torch.arange(2.,5)
before_change_datatype.dtype

torch.float32

In [40]:
after_change_datatype = before_change_datatype.type(torch.float16)
after_change_datatype.dtype

torch.float16

In [42]:
after_change_datatype = before_change_datatype.type(torch.int8)
after_change_datatype.dtype

torch.int8

**Tensor Information**

In [43]:
x = torch.rand(3,5)
x.shape, x.dtype, x.device

(torch.Size([3, 5]), torch.float32, device(type='cpu'))

**tensor Manipulation**

**Sum or Addition**

In [44]:
x = torch.tensor([1,2,3])
x + 15

tensor([16, 17, 18])

In [46]:
y = x+15
y

tensor([16, 17, 18])

In [47]:
z = x+y
z

tensor([17, 19, 21])

In [48]:
torch.add(x,y)

tensor([17, 19, 21])

**Substraction**

In [50]:
s = x-2
s

tensor([-1,  0,  1])

In [49]:
s = x-y
s

tensor([-15, -15, -15])

In [51]:
s = torch.sub(x,y)
s

tensor([-15, -15, -15])

**Multiplication Elements-wise**

In [52]:
M = x * 10
M

tensor([10, 20, 30])

In [54]:
M = torch.mul(x,20)
M

tensor([20, 40, 60])

In [55]:
M = x*x
M

tensor([1, 4, 9])

**Division**

In [56]:
D = x /2
D

tensor([0.5000, 1.0000, 1.5000])

In [57]:
D = x/y
D

tensor([0.0625, 0.1176, 0.1667])

**Matrix Multiplication**

In [60]:
matrix_a = torch.tensor([[1,2,3],
                        [4,5,6]])
matrix_b = torch.tensor([[7,8,9],
                        [7,6,5]])
matrix_a, matrix_b

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[7, 8, 9],
         [7, 6, 5]]))

In [61]:
matrix_a.shape , matrix_b.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [66]:
matrix_a * matrix_b

tensor([[ 7, 16, 27],
        [28, 30, 30]])

In [63]:
matrix_c = matrix_b.T
matrix_c.shape

torch.Size([3, 2])

In [65]:
mul_matrix = matrix_a @ matrix_c
mul_matrix

tensor([[ 50,  34],
        [122,  88]])

In [67]:
torch.mm(matrix_a,matrix_c)

tensor([[ 50,  34],
        [122,  88]])

In [69]:
torch.matmul(matrix_a,matrix_c)

tensor([[ 50,  34],
        [122,  88]])