In [71]:
import torch

**Shape Errors In Deep Learning**

In [5]:
a = torch.tensor([[1,2,3],
                  [1,2,1]])
b = torch.tensor([[1,2,3],
                  [2,3,6]])
a.shape , b.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [6]:
a @ b

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [7]:
c = b.T # take tranpose of matrix b and save in c
c.shape

torch.Size([3, 2])

In [8]:
a @ c

tensor([[14, 26],
        [ 8, 14]])

In [10]:
a = torch.tensor([[1,2],
                  [1,2]])
b = torch.tensor([[1,2,3],
                  [2,3,6]])
a.shape , b.shape

(torch.Size([2, 2]), torch.Size([2, 3]))

In [11]:
a@b # output will be in outer dimension of matrix  a and b as 2 x 3

tensor([[ 5,  8, 15],
        [ 5,  8, 15]])

**Min, Max , Mean and Sum etc**

In [13]:
x = torch.arange(1,100)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
min = x.min()
min

tensor(1)

In [18]:
max = x.max()
max

tensor(99)

In [19]:
sum = x.sum()
sum

tensor(4950)

In [23]:
x = torch.arange(1.,10.)
mean = x.mean()
mean

tensor(5.)

**POSITIONAL Min and Max**

In [24]:
sample = torch.arange(5,50,5)
sample

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [25]:
torch.min(sample)

tensor(5)

In [26]:
torch.argmin(sample)

tensor(0)

In [27]:
torch.max(sample)

tensor(45)

In [30]:
sample.argmax()

tensor(8)

# **Reshaping, Stacking, Squeezing, Unsequeeze, Permute**

**Reshape**

In [7]:
X = torch.arange(1,11)
X

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
X.reshape(2,5)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [10]:
X.reshape(5,2)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [23]:
X = torch.arange(1,61)
X

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60])

In [24]:
X.reshape(2,30)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
         49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [25]:
X.reshape(3,4,5)

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30],
         [31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40]],

        [[41, 42, 43, 44, 45],
         [46, 47, 48, 49, 50],
         [51, 52, 53, 54, 55],
         [56, 57, 58, 59, 60]]])

In [21]:
X = torch.arange(1,13)
X

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
X.reshape(2,6)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [16]:
X.reshape(3,4)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [20]:
X.reshape(2,3,2)

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

**View**

In [31]:
xx = torch.arange(1,9)
xx

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
yy = xx.view(2,4)
yy

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [39]:
yy[0,0] = 100
yy

tensor([[100,   2,   3,   4],
        [  5,   6,   7,   8]])

In [40]:
xx

tensor([100,   2,   3,   4,   5,   6,   7,   8])

In [41]:
yy[1,0] =50
yy

tensor([[100,   2,   3,   4],
        [ 50,   6,   7,   8]])

In [42]:
xx

tensor([100,   2,   3,   4,  50,   6,   7,   8])

**Stacking**

In [48]:
stack = torch.arange(1,17)
stack

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [49]:
stack_a =  torch.stack([stack,stack,stack],dim = 0)
stack_a

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [50]:
stack_a =  torch.stack([stack,stack],dim = 1)
stack_a

tensor([[ 1,  1],
        [ 2,  2],
        [ 3,  3],
        [ 4,  4],
        [ 5,  5],
        [ 6,  6],
        [ 7,  7],
        [ 8,  8],
        [ 9,  9],
        [10, 10],
        [11, 11],
        [12, 12],
        [13, 13],
        [14, 14],
        [15, 15],
        [16, 16]])

In [54]:
stack_a.reshape(4,4,2)

tensor([[[ 1,  1],
         [ 2,  2],
         [ 3,  3],
         [ 4,  4]],

        [[ 5,  5],
         [ 6,  6],
         [ 7,  7],
         [ 8,  8]],

        [[ 9,  9],
         [10, 10],
         [11, 11],
         [12, 12]],

        [[13, 13],
         [14, 14],
         [15, 15],
         [16, 16]]])

**Unsqueeze**

In [55]:
before_unsqueeze = torch.arange(1.,11.)
before_unsqueeze

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [57]:
before_unsqueeze.shape, before_unsqueeze.ndim

(torch.Size([10]), 1)

In [58]:
after_unsqueeze = torch.unsqueeze(before_unsqueeze,dim =0)
after_unsqueeze

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [59]:
after_unsqueeze.shape,after_unsqueeze.ndim

(torch.Size([1, 10]), 2)

In [63]:
after_unsqueeze = torch.unsqueeze(before_unsqueeze,dim =1)
after_unsqueeze

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [61]:
after_unsqueeze.shape,after_unsqueeze.ndim

(torch.Size([10, 1]), 2)

**Squeeze**

In [64]:
squeeze = after_unsqueeze.squeeze()
squeeze

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [65]:
squeeze.shape, squeeze.ndim

(torch.Size([10]), 1)

**Permute**

In [66]:
p = torch.rand(2,3,3)
p

tensor([[[0.1006, 0.7107, 0.4581],
         [0.0063, 0.3642, 0.4425],
         [0.1706, 0.7240, 0.9009]],

        [[0.8448, 0.8984, 0.8431],
         [0.2271, 0.9988, 0.2768],
         [0.2540, 0.3295, 0.5028]]])

In [67]:
p.shape

torch.Size([2, 3, 3])

In [68]:
permutee = p.permute(2,1,0)
permutee

tensor([[[0.1006, 0.8448],
         [0.0063, 0.2271],
         [0.1706, 0.2540]],

        [[0.7107, 0.8984],
         [0.3642, 0.9988],
         [0.7240, 0.3295]],

        [[0.4581, 0.8431],
         [0.4425, 0.2768],
         [0.9009, 0.5028]]])

In [69]:
permutee.shape

torch.Size([3, 3, 2])

In [70]:
permutee = p.permute(2,0,1)
permutee

tensor([[[0.1006, 0.0063, 0.1706],
         [0.8448, 0.2271, 0.2540]],

        [[0.7107, 0.3642, 0.7240],
         [0.8984, 0.9988, 0.3295]],

        [[0.4581, 0.4425, 0.9009],
         [0.8431, 0.2768, 0.5028]]])

**Indexing**

In [72]:
x = torch.arange(1,10).reshape(1,3,3)
x.shape

torch.Size([1, 3, 3])

In [73]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [74]:
x[0,0]

tensor([1, 2, 3])

In [76]:
x[0,2]

tensor([7, 8, 9])

In [77]:
x[0,0,0]

tensor(1)

In [78]:
x[0,0,2]

tensor(3)

In [79]:
x[0,2,2]

tensor(9)

**Pytorch Tensor and Numpy**

In [80]:
import numpy as np


In [81]:
array = np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
tensor = torch.from_numpy(array)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
Numpy= tensor.numpy()
Numpy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**Reproducibility**

In [86]:
a = torch.rand(3,4)
b = torch.rand(3,4)
a,b

(tensor([[0.9155, 0.9696, 0.2771, 0.4848],
         [0.9290, 0.8018, 0.9201, 0.4315],
         [0.6263, 0.9802, 0.8704, 0.5343]]),
 tensor([[0.0842, 0.9461, 0.3512, 0.1579],
         [0.9789, 0.6982, 0.2030, 0.7814],
         [0.6704, 0.7805, 0.1562, 0.7086]]))

In [88]:
torch.manual_seed(42)
c = torch.rand(3,4)
c

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [90]:
torch.manual_seed(42)
d = torch.rand(3,4)
d

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

**Use GPU**

In [91]:
torch.cuda.is_available()

False

In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [3]:
torch.cuda.device_count()

1

In [6]:
tensor = torch.tensor([1,2,2,2,2])
tensor.device

device(type='cpu')

In [9]:
tensor_gpu =tensor.to(device)

In [10]:
tensor_gpu.device

device(type='cuda', index=0)

In [11]:
tensor_back_cpu = tensor.cpu()
tensor_back_cpu.device

device(type='cpu')